#!/usr/bin/env python3
"""
Fetch Firebase Web Config Script

This script fetches the Firebase web app configuration from the Firebase project
and updates the login page with the correct configuration values.

Prerequisites:
- Service account with Firebase Admin role
- GOOGLE_APPLICATION_CREDENTIALS environment variable set

Usage:
    python scripts/fetch_firebase_config.py
"""

import os
import sys
import json
import re
import requests
from typing import Optional, Dict, Any


PROJECT_ID = "digital-workshop-hub"
FIREBASE_PROJECT_DIR = os.path.expanduser("~/repos/digital-workshop-hub")


def get_access_token() -> Optional[str]:
    """Get an access token using the service account credentials."""
    try:
        from google.oauth2 import service_account
        from google.auth.transport.requests import Request
        
        creds_path = os.environ.get('GOOGLE_APPLICATION_CREDENTIALS')
        if not creds_path:
            print("ERROR: GOOGLE_APPLICATION_CREDENTIALS not set")
            return None
        
        if not os.path.exists(creds_path):
            print(f"ERROR: Credentials file not found: {creds_path}")
            return None
        
        SCOPES = [
            'https://www.googleapis.com/auth/cloud-platform',
            'https://www.googleapis.com/auth/firebase'
        ]
        
        credentials = service_account.Credentials.from_service_account_file(
            creds_path,
            scopes=SCOPES
        )
        
        credentials.refresh(Request())
        return credentials.token
        
    except ImportError:
        print("ERROR: google-auth package not installed")
        print("Run: pip install google-auth google-auth-oauthlib")
        return None
    except Exception as e:
        print(f"ERROR: Could not get access token: {e}")
        return None


def get_firebase_web_apps(token: str) -> Optional[list]:
    """Get list of Firebase web apps for the project."""
    url = f"https://firebase.googleapis.com/v1beta1/projects/{PROJECT_ID}/webApps"
    headers = {
        'Authorization': f'Bearer {token}',
        'Content-Type': 'application/json'
    }
    
    response = requests.get(url, headers=headers)
    
    if response.status_code == 200:
        data = response.json()
        return data.get('apps', [])
    else:
        print(f"ERROR: Could not fetch web apps: {response.status_code}")
        print(response.text)
        return None


def get_web_app_config(token: str, app_id: str) -> Optional[Dict[str, Any]]:
    """Get the configuration for a specific web app."""
    url = f"https://firebase.googleapis.com/v1beta1/projects/{PROJECT_ID}/webApps/{app_id}/config"
    headers = {
        'Authorization': f'Bearer {token}',
        'Content-Type': 'application/json'
    }
    
    response = requests.get(url, headers=headers)
    
    if response.status_code == 200:
        return response.json()
    else:
        print(f"ERROR: Could not fetch web app config: {response.status_code}")
        print(response.text)
        return None


def update_login_page_config(config: Dict[str, Any]) -> bool:
    """Update the login page with the Firebase configuration."""
    login_page_path = os.path.join(FIREBASE_PROJECT_DIR, 'public', 'index.html')
    
    if not os.path.exists(login_page_path):
        print(f"ERROR: Login page not found: {login_page_path}")
        return False
    
    with open(login_page_path, 'r') as f:
        content = f.read()
    
    # Build the new config object
    new_config = f'''const firebaseConfig = {{
            apiKey: "{config.get('apiKey', '')}",
            authDomain: "{config.get('authDomain', '')}",
            projectId: "{config.get('projectId', '')}",
            storageBucket: "{config.get('storageBucket', '')}",
            messagingSenderId: "{config.get('messagingSenderId', '')}",
            appId: "{config.get('appId', '')}"
        }};'''
    
    # Replace the placeholder config
    pattern = r'const firebaseConfig = \{[^}]+\};'
    updated_content = re.sub(pattern, new_config, content)
    
    if updated_content == content:
        print("WARNING: Could not find config placeholder to replace")
        return False
    
    with open(login_page_path, 'w') as f:
        f.write(updated_content)
    
    print(f"Updated: {login_page_path}")
    return True


def create_firebase_config_file(config: Dict[str, Any]) -> bool:
    """Create a firebase-config.js file with the configuration."""
    config_path = os.path.join(FIREBASE_PROJECT_DIR, 'public', 'firebase-config.js')
    
    config_content = f'''// Firebase configuration for {PROJECT_ID}
// Auto-generated by fetch_firebase_config.py

const firebaseConfig = {{
    apiKey: "{config.get('apiKey', '')}",
    authDomain: "{config.get('authDomain', '')}",
    projectId: "{config.get('projectId', '')}",
    storageBucket: "{config.get('storageBucket', '')}",
    messagingSenderId: "{config.get('messagingSenderId', '')}",
    appId: "{config.get('appId', '')}"
}};

export default firebaseConfig;
'''
    
    with open(config_path, 'w') as f:
        f.write(config_content)
    
    print(f"Created: {config_path}")
    return True


def main():
    print("=" * 50)
    print("Fetch Firebase Web Config")
    print("=" * 50)
    print(f"\nProject: {PROJECT_ID}")
    print()
    
    # Get access token
    print("Getting access token...")
    token = get_access_token()
    if not token:
        print("\n[FAILED] Could not get access token")
        return 1
    print("  OK")
    
    # Get web apps
    print("\nFetching Firebase web apps...")
    apps = get_firebase_web_apps(token)
    if not apps:
        print("No web apps found for this project")
        print(f"\nCreate a web app at: https://console.firebase.google.com/project/{PROJECT_ID}/settings/general")
        return 1
    
    print(f"Found {len(apps)} web app(s)")
    
    # Get config for the first web app
    app = apps[0]
    app_id = app.get('appId', '').split('/')[-1]
    app_name = app.get('displayName', 'Unnamed')
    
    print(f"\nUsing web app: {app_name} ({app_id})")
    
    print("\nFetching web app configuration...")
    config = get_web_app_config(token, app_id)
    if not config:
        print("\n[FAILED] Could not fetch web app config")
        return 1
    
    print("  API Key:", config.get('apiKey', '')[:20] + "..." if config.get('apiKey') else "Not set")
    print("  Auth Domain:", config.get('authDomain', ''))
    print("  Project ID:", config.get('projectId', ''))
    print("  Storage Bucket:", config.get('storageBucket', ''))
    print("  App ID:", config.get('appId', '')[:30] + "..." if config.get('appId') else "Not set")
    
    # Update login page
    print("\nUpdating login page configuration...")
    if update_login_page_config(config):
        print("  OK")
    
    # Create config file
    print("\nCreating firebase-config.js...")
    if create_firebase_config_file(config):
        print("  OK")
    
    print("\n" + "=" * 50)
    print("Firebase Config Updated!")
    print("=" * 50)
    print(f"\nYou can now deploy the login page:")
    print(f"  cd {FIREBASE_PROJECT_DIR}")
    print(f"  firebase deploy --only hosting --project {PROJECT_ID}")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
